Initial commit of the bootstrap role
stuvusIT/bootstrap-ubuntu-rpi3 pull request #1
Opened 2017-04-15 13:29 UTC by dasJ

2017-04-16 11:38 UTC, SlothOfAnarchy requested changes

2017-04-16 11:38 UTC, SlothOfAnarchy commented on README.md
> +| `global_cores`     | :heavy_check_mark: | `1`     | Amount of CPU cores in the control machine to build with                                      |
why do you have a default if the var is mandatory? Same with the other vars below.

2017-04-16 11:38 UTC, SlothOfAnarchy commented on README.md
> +- [Janne Heß](https://github.com/dasJ)
please add your stuvus email

2017-04-16 11:38 UTC, SlothOfAnarchy commented on tasks/boot.yml
> +- name: Create fstab
maybe extract the tasks that have nothing to do with /boot

2017-04-16 11:38 UTC, SlothOfAnarchy commented on tasks/debootstrap.yml
> +       http://ports.ubuntu.com/
is there no https version or a way to verify hashes/signatures?

2017-04-16 11:38 UTC, SlothOfAnarchy commented on README.md
> +| `bootstrap_extraversion`   | :heavy_check_mark: | `+stuvus` | Extraversion to append on the kernel                     |
why is the extra version mandatory?

2017-04-16 11:38 UTC, SlothOfAnarchy commented on tasks/mount.yml
> +- name: Make boot directory
"Create"

2017-04-16 11:38 UTC, SlothOfAnarchy commented on README.md
> +| `bootstrap_root_password` | :heavy_multiplication_x: |         | Password to set for the root user                  |
describe the kind of hash that is expected

2017-04-16 18:17 UTC, dasJ commented on README.md
> +| `global_cores`     | :heavy_check_mark: | `1`     | Amount of CPU cores in the control machine to build with                                      |
You could unset it, or is this impossible in Ansible?

2017-04-16 18:17 UTC, dasJ commented on README.md
> +| `bootstrap_extraversion`   | :heavy_check_mark: | `+stuvus` | Extraversion to append on the kernel                     |
You don't need it. The kernel will have a shorter version number, then

2017-04-16 18:18 UTC, dasJ commented on README.md
> +- [Janne Heß](https://github.com/dasJ)
But I don't wish to receive mail

2017-04-16 18:18 UTC, dasJ commented on tasks/boot.yml
> +- name: Create fstab
See comment in the first line. These tasks make the Pi bootable

2017-04-16 18:18 UTC, dasJ commented on tasks/debootstrap.yml
> +       http://ports.ubuntu.com/
Sadly, no. But the packages are verified against the Ubuntu keyring before extracting

2017-04-16 18:21 UTC, dasJ commented
@SlothOfAnarchy Pls rereview

2017-04-17 14:13 UTC, SlothOfAnarchy commented on tasks/boot.yml
> +- name: Create fstab
I don't see a comment in the first line?

2017-04-17 14:16 UTC, SlothOfAnarchy commented on README.md
> +| `global_cores`     | :heavy_check_mark: | `1`     | Amount of CPU cores in the control machine to build with                                      |
Still a confusing approach to describe vars that need to be set. Your :heavy_check_mark: leaves the impression that the user **has** to set it.

2017-04-17 14:19 UTC, SlothOfAnarchy commented on README.md
> +| `bootstrap_extraversion`   | :heavy_check_mark: | `+stuvus` | Extraversion to append on the kernel                     |
Dont mark it as mandatory then?

2017-04-25 11:26 UTC, SlothOfAnarchy commented
please fix the required changes.

2017-04-30 18:37 UTC, dasJ commented
@SlothOfAnarchy Pls rereview

2017-04-30 18:39 UTC, dasJ commented on tasks/boot.yml
> +- name: Create fstab
Looks like I removed it

2017-04-30 19:30 UTC, SlothOfAnarchy commented on tasks/partitions.yml
> +    part_start: "{{ bootstrap_boot_size | mandatory }}"
why do you use the mandatory filter? `bootstrap_boot_size` is set by default.

2017-04-30 19:30 UTC, SlothOfAnarchy commented on tasks/partitions.yml
> +  when: "not 'ext4' in fatpart.stdout"
why do you only check against ext4?

2017-04-30 23:57 UTC, dasJ commented on tasks/partitions.yml
> +  when: "not 'ext4' in fatpart.stdout"
The filesystem module does that. However, it does not support FAT

2017-05-01 09:22 UTC, SlothOfAnarchy commented on tasks/partitions.yml
> +  when: "not 'ext4' in fatpart.stdout"
I meant your `when` condition

2017-05-01 13:51 UTC, dasJ commented on tasks/partitions.yml
> +  when: "not 'ext4' in fatpart.stdout"
It was supposed to mean fat...

2017-05-01 19:49 UTC, SlothOfAnarchy approved these changes

2017-05-01 19:50 UTC, merged